### ISSUE TITLE
Progress Box

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/apps#15]
![In Progress](https://user-images.githubusercontent.com/883655/100918362-0b7d9e80-34e1-11eb-87a7-a9b88baf0383.png)

![Uploaded](https://user-images.githubusercontent.com/883655/100918440-23edb900-34e1-11eb-9b36-e0f9c2437c96.png)

**Progress Form**

Progress form

**Includes:** Text Labels, Icons

**Relevant user story:** [User story](https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit)

**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=3584%3A2539)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic Do we need this already in the "file upload" flow for 0.24? Just thinking if we have this type of view after the user has selected the file to upload

**Comment by hamzahalilovic** [comment]
@mmlampinen It's not needed. This is also "old version", functionality anyway will need to be done no matter how it looks.
