### ISSUE TITLE
Global Navigation

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/apps#17]
<img width="80" alt="Screenshot 2020-11-03 at 01 47 59" src="https://user-images.githubusercontent.com/26879042/97934720-bed66480-1d76-11eb-935d-73ee65cc4c37.png">

**Global Navigation**

Global Navigation

**Includes:**  Icons

**Relevant user story:** [User story](https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit)

**Visual component design:** [Figma file](https://www.figma.com/file/cdQJSNK0F9OF6PtLOcMBk9/A1.3.-Data-Console-v.MVP?node-id=85%3A0)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic Per Valto's advice, this will be replaced by the user menu, so we can close this issue.

**Comment by hamzahalilovic** [comment]
Great!
