### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/apps#31]
<img width="230" alt="Screenshot 2020-11-05 at 15 38 58" src="https://user-images.githubusercontent.com/26879042/98254905-1fcf8980-1f7d-11eb-9675-5545aebd8f2e.png">

**Input**

Input field may include dropdown, placeholders, Input label..

**Includes:** 

**Relevant user story:** [User story](https://docs.google.com/document/d/1J5iiOgJnjcFXOFnN11Ra7lGb-JSI9clSLA899GNJC3o/edit)

**Visual component design:** [Figma file](https://www.figma.com/file/cdQJSNK0F9OF6PtLOcMBk9/A1.3.-Data-Console-v.MVP?node-id=7%3A30)

**Specifications:**

**Comment by mmlampinen** [comment]
@hamzahalilovic Don't we have something already in the alpha app or blend for this?
