### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/apps#39]
**Card Component**

**Includes:** 

1. **Message Form Box**
Message Form

![](https://user-images.githubusercontent.com/26879042/97934838-1e347480-1d77-11eb-88d9-d9333d3651c3.png)

**Relevant user story:** [User story](https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit)
**Visual component design:** [Figma file](https://www.figma.com/file/cdQJSNK0F9OF6PtLOcMBk9/A1.3.-Data-Console-v.MVP?node-id=85%3A0)

2. **Progress Form Box** 
Progress form

![](https://user-images.githubusercontent.com/883655/100918362-0b7d9e80-34e1-11eb-87a7-a9b88baf0383.png)

![](https://user-images.githubusercontent.com/883655/100918440-23edb900-34e1-11eb-9b36-e0f9c2437c96.png)

**Relevant user story:** [User story](https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit)
**Visual component design:** [Figma file](https://www.figma.com/file/fS9gcgUb0KShgtZ3XIYQqY/Production-Version-Software-Development?node-id=3584%3A2539)

3. **Upload Data Element Box**
The current console model supports 4 formats to upload the data in: archive, documents, images, and spreadsheets. There is a note that lets the user we are working on adding additional formats.

![](https://user-images.githubusercontent.com/26879042/97934405-ea0c8400-1d75-11eb-99fa-a041775bc671.png)

**Relevant user story:** [User story](https://docs.google.com/document/d/12GXNUdyK75S2Kdvh-wN2kQ6SBNJj5bIZpWDn-8Xkc6s/edit)
**Visual component design:** [Figma file](https://www.figma.com/file/cdQJSNK0F9OF6PtLOcMBk9/A1.3.-Data-Console-v.MVP?node-id=85%3A0)

**Specifications**: 

props {     
// with comments as necessary and helpful // 
}

**Completion Status**
- [x] Screenshot
- [x] Title 
- [x] Summary
- [x] Includes
- [x] User Story 
- [ ] Specifications
- [x] Label
- [x] Project
- [x] Milestone

*Guidelines:* ["GitHub Issue Card Template"](https://docs.google.com/document/d/1kyk7G7o19gZscVL-TEA1p1nVmP2NYk0Gf2w_MCcgXgk/edit#heading=h.antcpmcoy5u2)

**Comment by prifina-admin** [comment]
@hamzahalilovic  Blend already has same name component...
