### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by hamzahalilovic** [prifina/apps#47]
**1. Data Console Page Forms Tab**

![](https://user-images.githubusercontent.com/26879042/98255093-52798200-1f7d-11eb-8410-17b1a5283722.png)

*Summary narrative*

**Includes:** **3 Tabs: new forms, in progress forms, and completed forms.**

**Relevant user story:** [User story](https://docs.google.com/document/d/1J5iiOgJnjcFXOFnN11Ra7lGb-JSI9clSLA899GNJC3o/edit)
**Visual component design:** [Figma file](https://www.figma.com/file/cdQJSNK0F9OF6PtLOcMBk9/A1.3.-Data-Console-v.MVP?node-id=7%3A30)

**Specifications**: 

props {     
// with comments as necessary and helpful // 
}

**Completion Status**
- [ ] Screenshot
- [ ] Title 
- [ ] Summary
- [ ] Includes
- [ ] User Story 
- [ ] Specifications
- [ ] Label
- [ ] Project
- [ ] Milestone

*Guidelines:* ["GitHub Issue Card Template"](https://docs.google.com/document/d/1kyk7G7o19gZscVL-TEA1p1nVmP2NYk0Gf2w_MCcgXgk/edit#heading=h.antcpmcoy5u2)

**Comment by prifina-admin** [comment]
@hamzahalilovic  this is not "really" tab component...  tab component is like in usermenu ->settings
